package voipttt

import "strings"

// PhoneNumber is the phone number of a playing client.
type PhoneNumber string

// AnonymizedPhoneNumber is the anonymized phone number that
// gets sent to the opponent.
type AnonymizedPhoneNumber PhoneNumber

// Anonymized anonymizes the phone number so that it can be sent
// to the opponent.
func (pn *PhoneNumber) Anonymized() AnonymizedPhoneNumber {
	number := string(*pn)

	// Always fully anonymize when the number is shorter than this.
	if len(number) < 8 {
		return AnonymizedPhoneNumber(strings.Repeat("*", len(number)))
	}

	// Anonymize until the last two digits.
	const offset = 2
	normal := number[len(number)-offset:]
	anonymized := strings.Repeat("*", len(number)-offset) + normal

	return AnonymizedPhoneNumber(anonymized)
}

// VerificationCode is the code generated by the server
// that the client has to send in order for them to play.
type VerificationCode uint64

// WebhookURL is a URL which the server will call in order
// to get more information from the client.
type WebhookURL string

// RegisterClientRequest is used when calling the private API
// to confirm a verification code and to setup webhooks for further
// communication.
type RegisterClientRequest struct {
	VerificationCode  VerificationCode `json:"verificationCode"`
	ClientPhoneNumber PhoneNumber      `json:"clientPhoneNumber"`
	SelectDigitURL    WebhookURL       `json:"selectDigitUrl"`
	HeartbeatURL      WebhookURL       `json:"heartbeatUrl"`
	GameDoneURL       WebhookURL       `json:"gameDoneUrl"`
	GameStartURL      WebhookURL       `json:"gameStartUrl"`
}

// ReceiveDigitRequest is used when making a private API call to
// a webhook to get a new digit from a client.
type ReceiveDigitRequest struct {
	Digit int `json:"digit"`
}
